- hosts: all
  roles:
    - common

- hosts: lb
  roles:
    - loadbalancer
    
- hosts: k8s
  roles:
    - kubeadm

- hosts: master
  roles:
    - master

- hosts: dashboard
  roles:
    - dashboard

- hosts: workers
  roles:
    - workers