---
# tasks file for minions
- name: Reset Kubernetes
  shell: kubeadm reset -f
  register: kubeadm_reset

- name: Generate join token
  delegate_to: "{{ groups['master'][0] }}"
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_cmd

- set_fact:
    kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"

- name: Join Kubernetes Cluster
  shell: "{{ kubeadm_join }} --ignore-preflight-errors=all"
  when: kubeadm_reset is succeeded

- name: Poke kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes
  register: kubelet_poke